# test-1 is a sample profile that can be used as template.
---
target_mapping:
  "test-1":
    - "master"
    - "node"
    - "controlplane"
    - "etcd"

master:
  components:
    - apiserver
    - scheduler
    - controllermanager
    - etcd

  apiserver:
    bins:
      - kube-apiserver
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml

  scheduler:
    bins:
      - kube-scheduler
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml
    kubeconfig:
      - /var/lib/rancher/rke2/server/cred/scheduler.kubeconfig
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-scheduler.yaml

  controllermanager:
    bins:
      - kube-controller-manager
    confs:
      - /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml
    kubeconfig:
      - /var/lib/rancher/rke2/server/cred/controller.kubeconfig
    # yamllint disable-line
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/kube-controller-manager.yaml

  etcd:
    bins:
      - etcd
    datadirs:
      - /var/lib/rancher/rke2/server/db/etcd
    defaultconf: /var/lib/rancher/rke2/agent/pod-manifests/etcd.yaml

  node:
    components:
      - kubelet
      - proxy

    kubelet:
      defaultkubeconfig: /var/lib/rancher/rke2/agent/kubelet.kubeconfig
      defaultcafile: /var/lib/rancher/rke2/agent/client-ca.crt

    proxy:
      defaultkubeconfig: /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig

  policies:
    components:
      - policies
